# Built using the guide: 
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

# Objective:
# 0. Create development image for tests to run in. 
# 1. Test applications ( if applicable ) in their development containers. 
# 2. Build production images using docker-compose.
# 3. Push the production images to DockerHub.
# 4. Run an ansible playbook to deploy everything. 

stages:     
  - build-dev-images
  - build-api
  - build-ui
  - test-api
  - teardown-dev
  - build-production-images

.pre :
  - docker compose --file docker-compose.dev.yaml down
  - docker compose --file docker-compose.prod.yaml down

# Build the api using the typescript compiler.
# Hold on to build.
build-dev-images:
  tags: [ 'build-code' ]
  stage: build-dev-images
  script:
    # Exit code is still determined by docker-compose success.
    - echo "Building images using docker-compose."
    - docker compose --file docker-compose.dev.yaml up --detach --build
    - echo "Collecting dependancies..."

build-api:
  tags : [ 'build-code' ]
  stage: build-api
  script:
    - echo "Compiling typescript...."
    - docker exec api npx tsc
  artifacts:
    paths : [ ./api/dist ]

test-api:
  tags: [ 'test' ]
  stage: test-api
  script:
    - echo "Testing api..."
    - docker exec api npx jest

build-ui:
  tags : [ 'build-code' ]
  stage : build-ui
  script:
    - docker exec ui npm build
  artifacts :
    paths : [ ./ui/build ]


# Clean up to avoid potential naming conflicts.
teardown-dev:
  tags : [ 'test', 'build-containers' ]
  stage : 'teardown-dev'
  script :
    - docker compose --file docker-compose.dev.yaml down
    - docker compose --file docker-compose.prod.yaml down

# Build the ( production ) containers
build-production-images: 
  tags : [ 'build-containers' ]
  stage : 'build-production-images'
  script :
    - ls -lah api
    - ls -lah ui  #&& echo "Building docker images..."
    #- docker compose --file docker-compose.prod.yaml build && echo "Production docker images built."
