version : '3.7'
services :
  ssl :
    build :
      context : './nginx'
      dockerfile : 'Dockerfile.dev'
    container_name : 'ssl'
    networks :
      front : {}
      back : {}
    ports :
      - target : 443
        published : 443
        protocol : 'tcp'
  # Extender containers
  # I didn't know that this was possible. Sick af.
  api :
    extends :
      file : './api/docker-compose.dev.yaml'
      service : api
  
  mongodb : 
    container_name : mongodb
    extends :
      file : './api/docker-compose.dev.yaml'
      service : mongodb
  ux:
    extends :
      file : './ui/docker-compose.dev.yaml'
      service : ux
    networks :
      front : {}
      
networks :
  front :
    attachable : true
    driver : 'bridge'
  back :
    attachable : true
    driver : 'bridge'
