version : '3.7'
services :
  nginx : 
    build : 
      context : './nginx'
      dockerfile : './Dockerfile.dev'
    container_name : 'nginx'
    networks:
      - mondo
    ports : 
      - target : 80
        published : 80
        protocol : 'tcp'
    volumes :
      - type : 'bind'
        source : './post/.resources/'
        target : '/app/resources/'
  post :    
    build :
      context : './post'
      dockerfile : './Dockerfile.dev'
    container_name : 'post'
    networks:
      - mondo 
    ports :
      - target : 5000
        published : 5000
        protocol : 'tcp'
    volumes :
      - type : 'bind'
        source : './post/'
        target : '/app/'
networks :
  mondo : 
    driver : 'bridge'
    attachable : true









