# Install docker and docker-compose on both vms.
# Notes on shell scripts [ here ]( https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html )
# Notes on copy [ here ]( https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html )
---
- name : "Install docker"
  tags : [ install ]
  script : './install-docker.sh' 
  become : true


- name : "Install docker-compose."
  tags : [ install ]
  script : './install-docker-compose.sh'
  become : true


- name : "Make sure the docker group exists."
  group :
    name : docker
    state : present
