---
# tasks file for roles/app-runner
- name : "Create the application runner user."
  tags : [ "install", "security" ]
  user :
    name : app-runner
    groups : sudo,docker
    password : '{{password2}}'
  become : true

- name : "Change the vagrant user."
  tags : [ "install", "security" ]
  user :
    name : vagrant
    groups : sudo,docker
    password : '{{password3}}'
  become : true

- name : "Pull production images."
  tags : [ "deploy" ]
  docker :
