---
# tasks file for roles/app-runner
- name : "Create the app-runner user."
  tags : [ "install", "security", "app-runner" ]
  user :
    name : app-runner
    groups : sudo,docker
    password : '{{password2}}'
  become : true

- name : "Change the ansible users password."
  tags : [ "install", "security", "app-runner" ]
  user :
    name : ansible
    groups : sudo
    password : '{{password3}}'
  become : true

- name : "Change the ansible user."
  tags : [ "install", "security", "app-runner" ]
  user :
    name : vagrant
    groups : ''
    password : '{{password1}}'
  become : true

