---
# tasks file for roles/app-runner
- name : "Create the app-runner user."
  tags : [ "install", "security" ]
  user :
    name : app-runner
    groups : sudo,docker
    password : '{{password2}}'
  become : true

- name : "Change the ansible users password. No docker permissions."
  tags : [ "install", "security" ]
  user :
    name : ansible
    groups : sudo,docker
    password : '{{password3}}'
  become : true

  #- name : "Pull production images."
  #  tags : [ "deploy" ] 
  #  docker : 
