---
# vars file for backup
ansible_home : "/home/ansible"
remote_backups_dir : "{{ansible_home}}/backups"
local_backups_dir : "{{ansible_home}}/backups" # This is on the ansible runner, not to be confused with the remaining paths, which are in the target hosts.

mongo_data : "{{ansible_home}}/app/mongo_data"
mongo_data_archived : "{{remote_backups_dir}}/mongo_data.tar.gz"

npm_letsencrypt_data : "{{ansible_home}}/app/letsencrypt"
npm_letsencrypt_data_archived : "{{remote_backups_dir}}/letsencrypt.tar.gz"
npm_db_data : "{{ansible_home}}/app/data"
npm_db_data_archived : "{{remote_backups_dir}}/data.tar.gz"

mapping :
  "{{mongo_data}}" : "{{mongo_data_archived}}"
  "{{npm_letsencrypt_data}}" : "{{npm_letsencrypt_data_archived}}"
  "{{npm_db_data}}" : "{{npm_db_data_archived}}"

