FROM node
RUN mkdir /app/
WORKDIR /app/

# Install the environment. 
# The docker compose will mount this.
COPY yarn.lock .
COPY package.json .
RUN npm install .

ENTRYPOINT [ "npm" ]
CMD [ "start" ]
