- hosts : my_runner
  vars :
    env : 'dev'
  vars_files : 
    - "./vars/main.yml"
  roles : [ common, gitlab-runner ]
- hosts : my_server
  vars :
    env : 'dev'
  vars_files : 
    - "./vars/main.yml"
  roles : [ common, app-runner ]

