- hosts : my_runner
  vars :
    env : 'dev'
  vars_files : 
    - "./vars/main.yml"
    - "./vars/dockerhub.yml"
    - "./vars/api.env.yml"
  roles : [ common, gitlab-runner ]

- hosts : my_server
  vars :
    env : 'dev'
  vars_files : 
    - "./vars/main.yml"
    - "./vars/dockerhub.yml"
    - "./vars/api.env.yml"
  roles : [ common, app-runner ]

- hosts : dev
  roles : [ common ]
