# Rebuild hosts files
# echo ip addr for reuse in other scripts
echo '# This is an autogenerated file.'>../hosts.ini

echo '[my_runner]'>>../hosts.ini
addr1=$(vagrant.exe ssh gitlab-runner -c "ip address show eth0 | grep 'inet ' | sed -e 's/^.*inet //' -e 's/\/.*$//'")
echo $addr1
echo $addr1    ansible_connection=ssh    ansible_user=vagrant>>../hosts.ini

echo '[my_server]'>>../hosts.ini
addr2=$(vagrant.exe ssh app-runner -c "ip address show eth0 | grep 'inet ' | sed -e 's/^.*inet //' -e 's/\/.*$//'")>>../hosts.ini
echo $addr2
echo $addr2    ansible_connection=ssh    ansible_user=vagrant>>../hosts.ini
