---
- name : "Install gitlab-runner."
  tags : [ install ]
  become : true
  script : './install-gitlab-runner.sh'

- name : "Add the runner to the docker group and sudoers group."
  tags : [ install, security ]
  become : true
  user :
    name : gitlab-runner
    groups : docker,sudo
    password : '{{ password0 }}'
    
- name : "Change the vagrant password"
  tags : [ install, security ]
  become : true
  user :
    name : vagrant
    groups : sudo, docker
    password : '{{ password1 }}'



# - name : "Add a bashrc with aliases to the various profiles."
#   copy :
#     src : '../../resources/.bashrc'
#     dest : '/home/gitlab-runner/'
  
