---
# - name : "Install gitlab-runner."
#   tags : [ install, gitlab-runner ]
#   become : true
#   apt : 
#     deb : "https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_amd64.deb"
#     state : 'present'
# 
- name : "Add the runner to the docker group and sudoers group."
  tags : [ install, gitlab-runner ]
  become : true
  user :
    name : gitlab-runner
    groups : docker,sudo
    password : '{{ password0 }}'
    
- name : "Add the anisible user to the docker group."
  # This user is build in to the vagrantfiles
  tags : [ install, gitlab-runner, security ]
  become : true
  user :
    name : ansible
    groups : sudo,docker
    password : '{{ password1 }}'

- name : "Change the vagrant users password and remove it from the sudoers group."
  tags : [ install, gitlab-runner, security ]
  become : true
  user :
    name : vagrant
    password : '{{ password2 }}'

- name : "Add a .bashrc for gitlab-ci script to source important environment variables from."
  tags : [ "current2" ]
  become : true
  template :
    src : './.bashrc.j2'
    dest : '/home/gitlab-runner/.bashrc'

- name : "Set correct permissions for the gitlab-runner .bashrc"
  tags : [ "current2" ]
  become : true
  file :
    group : gitlab-runner
    owner : gitlab-runner
    path : /home/gitlab-runner/.bashrc
