---
- name : "Install gitlab-runner."
  tags : [ install, gitlab-runner ]
  become : true
  apt : 
    deb : "https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_amd64.deb"
    state : 'present'

- name : "Add the runner to the docker group and sudoers group."
  tags : [ install, gitlab-runner, current ]
  become : true
  user :
    name : gitlab-runner
    groups : docker,sudo
    password : '{{ password0 }}'
    
- name : "Add the anisible user to the docker group."
  # This user is build in to the vagrantfiles
  tags : [ install, gitlab-runner, security, current ]
  become : true
  user :
    name : ansible
    groups : sudo,docker
    password : '{{ password1 }}'

- name : "Change the vagrant users password and remove it from the sudoers group."
  tags : [ install, gitlab-runner, security ]
  become : true
  user :
    name : vagrant
    password : '{{ password2 }}'
    groups : ''


# - name : "Add a bashrc with aliases to the various profiles."
#   copy :
#     src : '../../resources/.bashrc'
#     dest : '/home/gitlab-runner/'
  
