version : '3.7'
services :
  ux:
    build :
      context : '.'
      dockerfile : './Dockerfile.dev'
    container_name : 'ui'
    ports : 
      - target : 8000
        published : 8000
        protocol : 'tcp'
    volumes :
      - type : 'bind'
        source : '.'
        target : '/app/'
      - '/app/node_modules'
      - '/app/build'
    tty: true
