FROM node:14

# Just use local packages.
# Install from inside container.
RUN echo 'node:node!' | chpasswd
RUN echo 'root:root!' | chpasswd

WORKDIR /app/
RUN chown node /app
RUN chmod +w /app
USER node


ENTRYPOINT [ "bash" ]
