FROM node
RUN mkdir /app/
WORKDIR /app/

# Install the environment. 
# The docker compose will mount this.
COPY package.json .
RUN npm install .
RUN npm update
RUN export NODE_OPTIONS=--openssl-legacy-provider

ENTRYPOINT [ "bash" ]
