version : '3.7'
services :
  api :
    build : 
      context : '.'
      dockerfile : 'Dockerfile.dev'
    container_name : 'api'
    environment :
      PORT : 9001
      DB_URI : 'mongodb://dev:goofy@mongodb?directConnection=true&serverSelectionTimeoutMS=2000'
    networks :
      mondo : {}
    ports : 
      - published : 9001
        target : 9001
        protocol : 'tcp'
    tty : True
    volumes :
      - type : 'bind'
        source : '.'
        target : '/app/'
  mongodb :
    container_name : 'mongodb'
    environment:
      MONGO_INITDB_ROOT_USERNAME : 'dev'
      MONGO_INITDB_ROOT_PASSWORD : 'goofy'
    image : 'mongo'
    networks :
      mondo : {}
    ports :
      - 27017
networks : 
  mondo :
    driver : 'bridge'
    attachable : true

