FROM node:alpine
WORKDIR /app/

RUN chown node /app/

# Passwords incase su is needed.
RUN echo 'root:Docker!' | chpasswd
RUN echo 'node:Node!' | chpasswd

# Install as node so that permissions don't ge messed up.
USER node
COPY ./package.json ./package-lock.json /app/
COPY dist ./dist
COPY .env.prod .
RUN npm ci

ENTRYPOINT npx env-cmd --file .env.prod node dist/index.js
