FROM node

# Create the app directory and change ownership to built in user.
WORKDIR /app/
RUN chown node /app/
RUN chmod +w /app/

# Passwords incase su is needed.
RUN echo 'root:Docker!' | chpasswd
RUN echo 'node:Node!' | chpasswd

# Install as node so that permissions don't ge messed up.
USER node
COPY package.json .
RUN npm install .

ENTRYPOINT bash
