version : '3.7'

services :

  api :

    build : 
      context : '.'
      dockerfile : 'Dockerfile.dev'
    container_name : 'api'
    networks :
      back : {}
    ports : 
      - published : 9001
        target : 9001
        protocol : 'tcp'
    tty : True
    volumes :
      - type : 'bind'
        source : '.'
        target : '/app/'
    depends_on : 
      - mongodb

  mongodb :

    container_name : 'mongodb'
    environment:
      MONGO_INITDB_ROOT_USERNAME : 'dev'
      MONGO_INITDB_ROOT_PASSWORD : 'goofy'
    image : 'mongo'
    networks :
      back : {}
    ports :
      - 27017


networks : 

  back :

    driver : 'bridge'
    attachable : true

