FROM node

# Passwords incase su is needed.
RUN echo 'root:Docker!' | chpasswd
RUN echo 'node:Node!' | chpasswd

WORKDIR /temp/
COPY package.json .
RUN npm install .

USER node
WORKDIR /app/
RUN mv temp/node_modules .

ENTRYPOINT bash
